### ISSUE TITLE
Base-music tarballs created are incompatible with OpenTTD client

### ISSUE THREAD

**Issue by nielsmh** [OpenTTD/bananas-api#59]
Based on <https://www.tt-forums.net/viewtopic.php?p=1234714#p1234714>

A ZIP file with a music set uploaded to BaNaNaS had the directory in the root of the ZIP file stripped, so all the contents are at the root of the generated TAR file. This causes OpenTTD to discard the downloaded file (see OpenTTD/OpenTTD#8283) as invalid, so while the download at first appears to have worked, it actually failed.

**Comment by TrueBrain** [comment]
As a FYI: bananas-server is only serving the content for the in-game client. The bananas-api handles uploads etc. So I moved this ticket.

I will need to investigate this, as this should never be possible: https://github.com/OpenTTD/bananas-api/blob/master/bananas_api/new_upload/session_publish.py

`tar_path` is never empty, and it forces all files to be in at least a single path. So this will be interesting to trace back :)

**Comment by TrueBrain** [comment]
The initial diagnostic is incorrect. The content of the tar is like:

```
Rise_of_the_Triad_OST_NST-1.0/00_chant_theme.mid
Rise_of_the_Triad_OST_NST-1.0/02_riseofthetriad.mid
Rise_of_the_Triad_OST_NST-1.0/04_godrestyedeadlygentlemen.mid
```

There is a root-folder there. And the tarball looks the same as other (hopefully working) base musics. Not sure what is going on, will investigate a bit further.

**Comment by TrueBrain** [comment]
Okay, this problem is a bit more subtle:

OpenTTD assumes that the very first entry in a base music tarball (and only for base music, as far as I can tell) is a "directory" entry, stating the initial directory. What makes this a bit tricky, that it heavily depends on the tar-specs if this is even allowed.

The original tar-format could only add files, symlinks or hardlinks. I believe `ustar` added support for these node types. For the new BaNaNaS, we could not find any (documented) reason to use `ustar` or `pax`, so we went with the oldest of all, not sure what OpenTTD could handle. This does not add an entry to indicate the directory as first entry.

For all content-downloads, using the old-format saves a few bytes and is easier to parse. But most downloads are not extracted by the client. Only base music is, I believe. So this problem only happens for base music.

So, this is a two-edged sword. There is nothing really wrong with the tarball, it is just that OpenTTD has a weird assumption on how it is created. This not-documented discrepancy between the OpenTTD client and BaNaNAS is what is breaking this.
Fixing OpenTTD by looking for the directory based on the filename would be the clean solution, but that would leave all current clients incompatible. So fixing BaNaNaS is the most compatible solution, but re-introduces an odd way of using tarballs. Assuming the first entry is a directory-entry with the prefix name, is a bit of a weird requirement to put onto tarballs.

But enfin, I will try to fix this on the BaNaNaS side, and repackage this tarball.

I would love for someone to validate my findings, especially that only base-music is affected by this.

**Comment by TrueBrain** [comment]
Minor addition:

https://github.com/OpenTTD/bananas-api/blob/master/bananas_api/new_upload/session_publish.py#L70

Turns out we already pack with `ustar`, which supports directories. So I guess it is only a matter of explicitly adding the directory as an entry.

**Comment by TrueBrain** [comment]
This problem should now be resolved, and any new uploads should work now.

The current uploaded file does not work; I am reluctant to manually fix the issue, so I see two possibilities:

1) we remove the current upload completely
2) the author uploads a new version, which does require some changes in some file before the upload will be accepted.

2) would be easiest, with the least amount of risk, but I have no problem diving into 1). Just let me know if it is needed :)

**Comment by FilmBoy84** [comment]
@TrueBrain Im more than happy to update the file
What exactly needs changing?

**Comment by TrueBrain** [comment]
@FilmBoy84 : I realised it might be hard for you to fix, and I did not realise before how easy it would be for me to fix. So I just fixed the upload in the backend. You can now download `Rise of the Triad OST NST` in-game without issue :) No further action required from your part!

w00p :)

**Comment by FilmBoy84** [comment]
That's fantastic, many thanks for sorting, can confirm it works
Will update my forum thread accordingly to say BaNaNaS now allows download
